var demoList = [{
    id: "leaflet100ThousandData",
    label: "leaflet加载10万数据",
    url: "leaflet-100ThousandData/demo.html"
}, {
    id: "leafletMapCorrection",
    label: "leaflet互联网地图纠偏插件",
    url: "leaflet-MapCorrection/demo.html"
}, {
    id: "LeafletShowHideLayerGroup",
    label: "Leaflet-通过LayerGroup控制大量、多种图层显示隐藏",
    url: "leaflet-ShowHideLayerGroup/demo.html"
}, {
    id: "LeafletPathDashFlow",
    label: "Leaflet-支持Canvas的Leaflet.Path.DashFlow动态流向线",
    url: "leaflet-PathDashFlow/demo.html"
}, {
    id: "LeafletPolylineDecorator",
    label: "Leaflet带箭头的线",
    url: "leaflet-PolylineDecorator/demo.html"
}, {
    id: "postGISbuffer",
    label: "为什么PostGIS中对点进行buffer分析得到的是个椭圆",
    url: "postGIS-buffer/index.html"
}, {
    id: "diviconError-CanvasMarker",
    label: "H5时代leaflet中还在用DivIcon，标签示例",
    url: "leaflet-divIconError/canvas-markers.html"
}, {
    id: "diviconError-LabelTextCollision",
    label: "H5时代leaflet中还在用DivIcon，文字标注示例",
    url: "leaflet-divIconError/LabelTextCollision.html"
}, {
    id: "LeafletOverlapMarkerPopup1",
    label: "leaflet可自动避让的气泡窗口-切换显示气泡",
    url: "leaflet-OverlapMarkerPopup/demo1.html"
}, {
    id: "LeafletOverlapMarkerPopup2",
    label: "leaflet可自动避让的气泡窗口-显示所有气泡",
    url: "leaflet-OverlapMarkerPopup/demo2.html"
}, {
    id: "LeafletOverlapMarkerPopup3",
    label: "leaflet可自动避让的气泡窗口-点击显示气泡",
    url: "leaflet-OverlapMarkerPopup/demo3.html"
}, {
    id: "MapboxGLPolylineDecorator",
    label: "mapboxgl实现带箭头轨迹线",
    url: "mapboxgl-PolylineDecorator/demo.html"
}, {
    id: "MapboxGL3DLine",
    label: "mapboxgl绘制3D线",
    url: "mapboxgl-3DLine/demo.html"
}, {
    id: "LeafletRouteAnimate",
    label: "Leaflet带箭头轨迹以及沿轨迹带方向的动态marker",
    url: "leaflet-RouteAnimate/demo.html"
}, {
    id: "PostGISConnect",
    label: "postgis连通性分析",
    url: "postgis-connect/index.html"
}, {
    id: "mapboxglMapCorrection2",
    label: "mapboxgl互联网地图纠偏插件（二）",
    url: "mapboxgl-MapCorrection2/GaoDeMap.html"
}, {
    id: "mapboxglMapCorrection3",
    label: "mapboxgl互联网地图纠偏插件（三）",
    href: "mapboxgl-MapCorrection3/gcj02TileLayer.html"
}, {
    id: "GISAlgorithm",
    label: "GIS常用算法",
    url: "GISAlgorithm/demo.html"
}, {
    id: "mapboxglMapCorrection4",
    label: "mapboxgl纠偏百度地图",
    url: "http://gisarmory.xyz/mapboxgl.InternetMapCorrection/examples/rasterTileLayer.html"
}, {
    id: "mapboxglStyleUniqueValue1",
    label: "mapboxgl地图样式-唯一值渲染-方式一",
    url: "mapboxgl-style-uniqueValue/demo/uniqueValue1.html"
}, {
    id: "mapboxglStyleUniqueValue2",
    label: "mapboxgl地图样式-唯一值渲染-方式二",
    url: "mapboxgl-style-uniqueValue/demo/uniqueValue2.html"
}, {
    id: "mapboxglStyleUniqueValue3",
    label: "mapboxgl地图样式-唯一值渲染-方式三",
    url: "mapboxgl-style-uniqueValue/demo/uniqueValue3.html"
}, {
    id: "mapboxglStyleUniqueValue4",
    label: "mapboxgl地图样式-唯一值渲染-方式四",
    url: "mapboxgl-style-uniqueValue/demo/uniqueValue4.html"
}, {
    id: "mapboxglStyleUniqueValue5",
    label: "mapboxgl地图样式-唯一值渲染-方式五",
    url: "mapboxgl-style-uniqueValue/demo/uniqueValue5.html"
}, {
    id: "mapboxglStyleReclass1",
    label: "mapboxgl地图样式-重分类渲染-方式一",
    url: "mapboxgl-style-reclass/demo/reclass1.html"
}, {
    id: "mapboxglStyleReclass2",
    label: "mapboxgl地图样式-重分类渲染-方式二",
    url: "mapboxgl-style-reclass/demo/reclass2.html"
}, {
    id: "mapboxglStyleReclass3",
    label: "mapboxgl地图样式-重分类渲染-方式三",
    url: "mapboxgl-style-reclass/demo/reclass3.html"
}, {
    id: "mapboxglStyleInterpolate1",
    label: "mapboxgl中插值表达式的应用场景-热力图",
    url: "mapboxgl-style-interpolate/demo/heatmap.html"
}, {
    id: "mapboxglStyleInterpolate2",
    label: "mapboxgl中插值表达式的应用场景-轨迹图1",
    url: "mapboxgl-style-interpolate/demo/trackSpeed1.html"
}, {
    id: "mapboxglStyleInterpolate3",
    label: "mapboxgl中插值表达式的应用场景-轨迹图2",
    url: "mapboxgl-style-interpolate/demo/trackSpeed2.html"
}
];