var blogList = [{
    id: "blogList",
    label: "博客列表",
    url: "README.md"
}, {
    id: "wechat",
    label: "公众号",
    url: "menu/wechat.md"
}, {
    id: "github",
    label: "github",
    href: "https://github.com/gisarmory",
}, {
    id: "aboutUs",
    label: "关于我们",
    url: "menu/aboutUs.md"
}, {
    id: "leaflet100ThousandData",
    label: "leaflet加载10万数据",
    url: "leaflet-100ThousandData/README.md"
}, {
    id: "leafletMapCorrection",
    label: "leaflet互联网地图纠偏插件",
    url: "leaflet-MapCorrection/README.md"
}, {
    id: "LeafletShowHideLayerGroup",
    label: "Leaflet-通过LayerGroup控制大量、多种图层显示隐藏",
    url: "leaflet-ShowHideLayerGroup/README.md"
}, {
    id: "LeafletPathDashFlow",
    label: "Leaflet-支持Canvas的Leaflet.Path.DashFlow动态流向线",
    url: "leaflet-PathDashFlow/README.md"
}, {
    id: "LeafletPolylineDecorator",
    label: "Leaflet带箭头的线",
    url: "leaflet-PolylineDecorator/README.md"
}, {
    id: "maputnikGeoserverVectorTiles",
    label: "maputnik加载geoserver发布的tms矢量瓦片",
    url: "maputnik-GeoserverVectorTiles/README.md"
}, {
    id: "postGISbuffer",
    label: "为什么PostGIS中对点进行buffer分析得到的是个椭圆",
    url: "postGIS-buffer/README.md"
}, {
    id: "diviconError",
    label: "H5时代leaflet中还在用DivIcon，标签示例",
    url: "leaflet-divIconError/README.md"
}, {
    id: "LeafletOverlapMarkerPopup",
    label: "leaflet如何优雅的展示重叠点位的气泡窗口",
    url: "leaflet-OverlapMarkerPopup/README.md"
}];