var demoList = [{
    id: "leaflet100ThousandData",
    label: "leaflet加载10万数据",
    url: "leaflet-100ThousandData/demo.html"
}, {
    id: "leafletMapCorrection",
    label: "leaflet互联网地图纠偏插件",
    url: "leaflet-MapCorrection/demo.html"
}, {
    id: "LeafletShowHideLayerGroup",
    label: "Leaflet-通过LayerGroup控制大量、多种图层显示隐藏",
    url: "leaflet-ShowHideLayerGroup/demo.html"
}, {
    id: "LeafletPathDashFlow",
    label: "Leaflet-支持Canvas的Leaflet.Path.DashFlow动态流向线",
    url: "leaflet-PathDashFlow/demo.html"
}, {
    id: "LeafletPolylineDecorator",
    label: "Leaflet带箭头的线",
    url: "leaflet-PolylineDecorator/demo.html"
}, {
    id: "postGISbuffer",
    label: "为什么PostGIS中对点进行buffer分析得到的是个椭圆",
    url: "postGIS-buffer/index.html"
}, {
    id: "diviconError-CanvasMarker",
    label: "H5时代leaflet中还在用DivIcon，标签示例",
    url: "leaflet-divIconError/canvas-markers.html"
}, {
    id: "diviconError-LabelTextCollision",
    label: "H5时代leaflet中还在用DivIcon，文字标注示例",
    url: "leaflet-divIconError/LabelTextCollision.html"
}, {
    id: "LeafletOverlapMarkerPopup1",
    label: "leaflet可自动避让的气泡窗口-切换显示气泡",
    url: "leaflet-OverlapMarkerPopup/demo1.html"
}, {
    id: "LeafletOverlapMarkerPopup2",
    label: "leaflet可自动避让的气泡窗口-显示所有气泡",
    url: "leaflet-OverlapMarkerPopup/demo2.html"
}, {
    id: "LeafletOverlapMarkerPopup3",
    label: "leaflet可自动避让的气泡窗口-点击显示气泡",
    url: "leaflet-OverlapMarkerPopup/demo3.html"
}, {
    id: "MapboxGLPolylineDecorator",
    label: "mapboxgl实现带箭头轨迹线",
    url: "mapboxgl-PolylineDecorator/demo.html"
}, {
    id: "LeafletRouteAnimate",
    label: "Leaflet带箭头轨迹以及沿轨迹带方向的动态marker",
    url: "leaflet-RouteAnimate/demo.html"
}
];