var sourceList = [{
    id: "leaflet100ThousandData",
    label: "leaflet加载10万数据",
    url: "https://github.com/gisarmory/gisarmory.blog/blob/master/leaflet-100ThousandData/demo.html"
}, {
    id: "leafletMapCorrection",
    label: "leaflet互联网地图纠偏插件",
    url: "https://github.com/gisarmory/Leaflet.InternetMapCorrection"
}, {
    id: "LeafletShowHideLayerGroup",
    label: "LeafletLayerGroup图层组控制显示隐藏",
    url: "https://github.com/gisarmory/Leaflet.ShowHideLayerGroup"
}, {
    id: "LeafletPathDashFlow",
    label: "Leaflet动态流向线",
    url: "https://github.com/gisarmory/Leaflet.PathDashFlow"
}, {
    id: "LeafletPolylineDecorator",
    label: "Leaflet带箭头的线",
    url: "https://github.com/gisarmory/Leaflet.PolylineDecorator"
}, {
    id: "postGISbuffer",
    label: "PostGIS中buffer函数脚本",
    url: "https://github.com/gisarmory/gisarmory.blog/blob/master/postGIS-buffer/postGIS-buffer.sql"
}, {
    id: "diviconError-CanvasMarker",
    label: "H5时代leaflet中还在用DivIcon，标签示例",
    url: "https://github.com/gisarmory/Leaflet.Canvas-Markers"
}, {
    id: "diviconError-LabelTextCollision",
    label: "H5时代leaflet中还在用DivIcon，文字标注示例",
    url: "https://github.com/gisarmory/Leaflet.LabelTextCollision"
}, {
    id: "LeafletOverlapMarkerPopup",
    label: "leaflet如何优雅的展示重叠点位的气泡窗口",
    url: "https://github.com/gisarmory/Leaflet.OverlapMarkerPopup"
}, {
    id: "MapboxGLPolylineDecorator",
    label: "mapboxgl实现带箭头轨迹线",
    url: "https://github.com/gisarmory/gisarmory.blog/tree/master/mapboxgl-PolylineDecorator/demo.html"
}, {
    id: "MapboxGL3DLine",
    label: "mapboxgl绘制3D线",
    url: "https://github.com/gisarmory/gisarmory.blog/tree/master/mapboxgl-3DLine/demo.html"
}, {
    id: "LeafletRouteAnimate",
    label: "Leaflet带箭头轨迹以及沿轨迹带方向的动态marker",
    url: "https://github.com/gisarmory/gisarmory.blog/tree/master/leaflet-RouteAnimate/demo.html"
}, {
    id: "LeafletAnimatedMarker",
    label: "Leaflet动态marker",
    url: "https://github.com/gisarmory/Leaflet.AnimatedMarker"
}, {
    id: "PostGISConnect",
    label: "PostGIS管网连通性分析脚本",
    url: "https://github.com/gisarmory/gisarmory.blog/blob/master/postgis-connect/analysis_connect.sql"
}, {
    id: "PostGISUpdateTopology",
    label: "PostGIS更新管网拓扑",
    url: "https://github.com/gisarmory/gisarmory.blog/blob/master/postgis-connect/analysis_updatetopology.sql"
}, {
    id: "PostGISPipeTest",
    label: "PostGIS管网测试库",
    url: "https://github.com/gisarmory/gisarmory.blog/blob/master/postgis-connect/data/postgis_pipetest.bak"
}, {
    id: "maputnikGeoserverVectorTiles",
    label: "maputnik",
    url: "https://github.com/gisarmory/editor"
}, {
    id: "mapboxglMapCorrection2",
    label: "互联网地图纠偏（二）",
    url: "https://github.com/gisarmory/gisarmory.blog/blob/master/mapboxgl-MapCorrection2/js/gcj02TileLayer.js"
}
];