var sourceList = [{
    id: "leaflet100ThousandData",
    label: "leaflet加载10万数据",
    url: "https://github.com/gisarmory/gisarmory.blog/blob/master/leaflet-100ThousandData/demo.html"
}, {
    id: "leafletMapCorrection",
    label: "leaflet互联网地图纠偏插件",
    url: "https://github.com/gisarmory/Leaflet.InternetMapCorrection"
}, {
    id: "LeafletShowHideLayerGroup",
    label: "LeafletLayerGroup图层组控制显示隐藏",
    url: "https://github.com/gisarmory/Leaflet.ShowHideLayerGroup"
}, {
    id: "LeafletPathDashFlow",
    label: "Leaflet动态流向线",
    url: "https://github.com/gisarmory/Leaflet.PathDashFlow"
}, {
    id: "LeafletPolylineDecorator",
    label: "Leaflet带箭头的线",
    url: "https://github.com/gisarmory/Leaflet.PolylineDecorator"
}, {
    id: "postGISbuffer",
    label: "PostGIS中buffer函数脚本",
    url: "https://github.com/gisarmory/gisarmory.blog/blob/master/postGIS-buffer/postGIS-buffer.sql"
}, {
    id: "diviconError-CanvasMarker",
    label: "H5时代leaflet中还在用DivIcon，标签示例",
    url: "https://github.com/gisarmory/Leaflet.Canvas-Markers"
}, {
    id: "diviconError-LabelTextCollision",
    label: "H5时代leaflet中还在用DivIcon，文字标注示例",
    url: "https://github.com/gisarmory/Leaflet.LabelTextCollision"
}];